### PR TITLE
website should not handle releases

### PR DESCRIPTION
**Pull request by joshgoebel**

### CODE REVIEW

**Comment by joshgoebel** [comment]
@isagalaev Does this look about right to you?

**Comment by joshgoebel** [comment]
This leaves the building of packages and NPM for our GitHub automation and of course the website still builds it's own CDN cache for purposes of the download page...

**Comment by isagalaev** [comment]
Thanks! I'll merge it and then add some more cleanup.

**Comment by isagalaev** [comment]
P.S. Deployed.

**Pull request merged**
